# Generated by Django 5.1.6 on 2025-02-14 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MileageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("적립", "적립"), ("사용", "사용")], max_length=10
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ride_date", models.DateField(default=django.utils.timezone.now)),
                ("ride_start_time", models.DateTimeField(blank=True, null=True)),
                ("ride_end_time", models.DateTimeField(blank=True, null=True)),
                ("usage_time", models.IntegerField(default=0)),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "frequent_route",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
